"""
recognizer.py
-------------
InsightFace face recognition — classifies each detected person as
known (enrolled) or unknown.

Why InsightFace over DeepFace here:
  - InsightFace runs faster on CPU (ArcFace backbone via ONNX)
  - DeepFace is kept available in enroll.py for enrollment flexibility
  - Both produce 512-d embeddings; cosine similarity is used for matching

The known face embeddings are loaded from data/embeddings.pkl which is
generated by setup/enroll.py before the system starts monitoring.

For each person bounding box from YOLOv8, this module:
  1. Crops and aligns the face region
  2. Computes embedding
  3. Compares against all enrolled embeddings via cosine similarity
  4. Returns "known" + name if above threshold, else "unknown"
"""

import cv2
import pickle
import numpy as np
import logging
from pathlib import Path
from insightface.app import FaceAnalysis

logger = logging.getLogger(__name__)

EMBEDDINGS_PATH = Path("data/embeddings.pkl")


class FaceRecognizer:
    def __init__(self, config: dict):
        self._threshold = config["thresholds"]["face_similarity_min"]

        logger.info("[recognizer] Loading InsightFace — first run downloads ONNX models")
        self._app = FaceAnalysis(
            name="buffalo_sc",          # lightweight model — good CPU performance
            providers=["CPUExecutionProvider"]
        )
        self._app.prepare(ctx_id=0, det_size=(320, 320))
        logger.info("[recognizer] InsightFace ready")

        self._known: dict[str, np.ndarray] = self._load_embeddings()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def recognize_all(self, frame: np.ndarray) -> list[dict]:
        """
        Run face recognition on the full frame.

        Returns
        -------
        List of face results:
            {
                "name"      : str,       # enrolled name or "unknown"
                "known"     : bool,
                "similarity": float,     # best cosine similarity score
                "bbox"      : [x1,y1,x2,y2],
            }
        """
        faces = self._app.get(frame)
        results = []

        for face in faces:
            emb  = face.embedding
            bbox = list(map(int, face.bbox.tolist()))
            name, sim = self._match(emb)
            results.append({
                "name":       name,
                "known":      name != "unknown",
                "similarity": round(sim, 3),
                "bbox":       bbox,
            })
            logger.debug(f"[recognizer] Face: {name} (sim={sim:.3f})")

        return results

    def unknown_count(self, face_results: list[dict]) -> int:
        return sum(1 for f in face_results if not f["known"])

    def reload_embeddings(self) -> None:
        """Hot-reload embeddings without restarting (call after new enrollment)."""
        self._known = self._load_embeddings()
        logger.info(f"[recognizer] Reloaded {len(self._known)} known identities")

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------
    def _match(self, embedding: np.ndarray) -> tuple[str, float]:
        """Return (name, similarity) for best matching known face."""
        if not self._known:
            return "unknown", 0.0

        best_name = "unknown"
        best_sim  = 0.0

        for name, known_emb in self._known.items():
            sim = self._cosine_similarity(embedding, known_emb)
            if sim > best_sim:
                best_sim  = sim
                best_name = name

        if best_sim < self._threshold:
            return "unknown", best_sim

        return best_name, best_sim

    @staticmethod
    def _cosine_similarity(a: np.ndarray, b: np.ndarray) -> float:
        denom = (np.linalg.norm(a) * np.linalg.norm(b))
        if denom == 0:
            return 0.0
        return float(np.dot(a, b) / denom)

    @staticmethod
    def _load_embeddings() -> dict[str, np.ndarray]:
        if not EMBEDDINGS_PATH.exists():
            logger.warning(
                "[recognizer] No embeddings found at data/embeddings.pkl — "
                "run setup/enroll.py first. Everyone will appear as unknown."
            )
            return {}
        with open(EMBEDDINGS_PATH, "rb") as f:
            data = pickle.load(f)
        logger.info(f"[recognizer] Loaded embeddings for: {list(data.keys())}")
        return data
